// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5jZUJ9AEMXQfIG_A2YPUl0TZCeLjjYew',
    appId: '1:526427305782:web:ec29abf23f24a442666597',
    messagingSenderId: '526427305782',
    projectId: 'plantdiseasedetection-20281',
    authDomain: 'plantdiseasedetection-20281.firebaseapp.com',
    storageBucket: 'plantdiseasedetection-20281.firebasestorage.app',
    measurementId: 'G-5K097QRG0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-m54V2HQ8aJIQgZezh0e3QDZWdV3oKek',
    appId: '1:526427305782:android:c76b0097a2be21f6666597',
    messagingSenderId: '526427305782',
    projectId: 'plantdiseasedetection-20281',
    storageBucket: 'plantdiseasedetection-20281.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHCz8AusVaY1Mwpmzf2ob3KcV5A7ZwIQA',
    appId: '1:526427305782:ios:93f1fb72c4f936a5666597',
    messagingSenderId: '526427305782',
    projectId: 'plantdiseasedetection-20281',
    storageBucket: 'plantdiseasedetection-20281.firebasestorage.app',
    iosBundleId: 'com.example.maizeplant',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHCz8AusVaY1Mwpmzf2ob3KcV5A7ZwIQA',
    appId: '1:526427305782:ios:93f1fb72c4f936a5666597',
    messagingSenderId: '526427305782',
    projectId: 'plantdiseasedetection-20281',
    storageBucket: 'plantdiseasedetection-20281.firebasestorage.app',
    iosBundleId: 'com.example.maizeplant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5jZUJ9AEMXQfIG_A2YPUl0TZCeLjjYew',
    appId: '1:526427305782:web:1e2232929ae4aa10666597',
    messagingSenderId: '526427305782',
    projectId: 'plantdiseasedetection-20281',
    authDomain: 'plantdiseasedetection-20281.firebaseapp.com',
    storageBucket: 'plantdiseasedetection-20281.firebasestorage.app',
    measurementId: 'G-7BN4B3RHH6',
  );

}